<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_To-do (1)</name>
   <tag></tag>
   <elementGuidId>7bb0cb93-f62c-4653-afab-1fdc34e42049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel1a-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='panel1a-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;To-do (1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9af4894b-343c-49d3-9d8e-487c0ee6d53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiAccordionSummary-root Mui-expanded css-t3szsf</value>
      <webElementGuid>5dd81b16-b5f2-403e-bcd9-2116e4c42331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da2bdc9b-ba7b-454e-bed7-4cf1610d0023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>afa4b4ab-cb64-4697-8436-2e0f2800f98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c369a37c-4ee2-456c-ab50-acc016b377f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>panel1a-content</value>
      <webElementGuid>c6f325f4-708b-4ae3-bccc-0e8c792cada5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panel1a-header</value>
      <webElementGuid>7fdc4d25-5a2f-464d-a161-a01d3fa2be0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alignitems</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ad398a1b-3315-4937-8026-dfbf51972080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>justifycontent</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>f879abd3-7d5e-4629-84c1-0cccd78c3fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>To-do (1)</value>
      <webElementGuid>838a2c1f-994b-4d28-b9a0-c603499d3c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App_App__B2Ebb&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row css-p1hrig&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-direction-xs-row MuiGrid2-grid-xs-12 MuiGrid2-grid-sm-6 css-18wkevi&quot;]/div[@class=&quot;MuiBox-root css-1v1qs4&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded Mui-expanded css-17m55b&quot;]/h3[@class=&quot;MuiAccordion-heading css-wnfue5&quot;]/button[@id=&quot;panel1a-header&quot;]</value>
      <webElementGuid>18d9b44b-1e3a-4360-ad2f-b47234a3a5b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='panel1a-header']</value>
      <webElementGuid>68c3269f-a0b7-4a76-bd29-f0252a6ce7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/h3/button</value>
      <webElementGuid>961f3aeb-2d2c-4976-8201-5ce288dbceca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::button[2]</value>
      <webElementGuid>5e3e3929-de90-4c59-b100-18df85308e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing Task 1'])[1]/preceding::button[1]</value>
      <webElementGuid>47af22f2-9147-4e52-9ab6-7d8275f305ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/button</value>
      <webElementGuid>08a3cf07-bcb6-4bf4-aed5-8f248f36ac9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'panel1a-header' and (text() = 'To-do (1)' or . = 'To-do (1)')]</value>
      <webElementGuid>7057da53-26f2-43ee-a6ec-19b2616cc03f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
