<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Testing TaskHigh2359, 04-01-25_1</name>
   <tag></tag>
   <elementGuidId>306da824-dd27-4a95-822d-f8edbd2c3065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-fv3lde</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel1a-content']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Testing TaskHigh23:59, 04-01-25&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29b64861-eb17-44e4-ba53-ed6c8347c2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-fv3lde</value>
      <webElementGuid>4cd772e9-0d86-480e-a529-e3e905d9fc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing TaskHigh23:59, 04-01-25</value>
      <webElementGuid>40512a27-4a50-4a2d-9306-b0d543a614a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App_App__B2Ebb&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row css-p1hrig&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-direction-xs-row MuiGrid2-grid-xs-12 MuiGrid2-grid-sm-6 css-18wkevi&quot;]/div[@class=&quot;MuiBox-root css-1v1qs4&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded Mui-expanded css-17m55b&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-1cbf1l2&quot;]/div[@class=&quot;MuiCollapse-wrapper MuiCollapse-vertical css-15830to&quot;]/div[@class=&quot;MuiCollapse-wrapperInner MuiCollapse-vertical css-9vd5ud&quot;]/div[@id=&quot;panel1a-content&quot;]/div[@class=&quot;MuiAccordionDetails-root css-bes99b&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-1gunrcb&quot;]/div[@class=&quot;MuiBox-root css-fv3lde&quot;]</value>
      <webElementGuid>98ade2ac-58a4-4e3e-a31b-379c1ca456a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel1a-content']/div/div/div/div</value>
      <webElementGuid>1e323a9f-8f22-465f-8ecb-ecc632a6a681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>b4b72464-cb52-4f23-b0e4-ee919bcb7d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Testing TaskHigh23:59, 04-01-25' or . = 'Testing TaskHigh23:59, 04-01-25')]</value>
      <webElementGuid>ee7f77d5-ed57-4cd5-89aa-d24fc3182bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
