<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Testing TaskHigh2359, 04-01-25 (2)</name>
   <tag></tag>
   <elementGuidId>689b249f-2494-4a52-a023-90472869092c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-fv3lde</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel1a-content']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Testing TaskHigh23:59, 04-01-25&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3d23132-3b54-4d14-8d88-40e3ece5f4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-fv3lde</value>
      <webElementGuid>0bf070f6-ae96-48b7-80e3-b8f72be266ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing TaskHigh23:59, 04-01-25</value>
      <webElementGuid>69281eb9-5278-42ef-8526-1c031161269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App_App__B2Ebb&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-container MuiGrid2-direction-xs-row css-p1hrig&quot;]/div[@class=&quot;MuiGrid2-root MuiGrid2-direction-xs-row MuiGrid2-grid-xs-12 MuiGrid2-grid-sm-6 css-18wkevi&quot;]/div[@class=&quot;MuiBox-root css-1v1qs4&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded Mui-expanded css-17m55b&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-1cbf1l2&quot;]/div[@class=&quot;MuiCollapse-wrapper MuiCollapse-vertical css-15830to&quot;]/div[@class=&quot;MuiCollapse-wrapperInner MuiCollapse-vertical css-9vd5ud&quot;]/div[@id=&quot;panel1a-content&quot;]/div[@class=&quot;MuiAccordionDetails-root css-bes99b&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-1gunrcb&quot;]/div[@class=&quot;MuiBox-root css-fv3lde&quot;]</value>
      <webElementGuid>ebc1564b-367f-40d2-90ac-b744e36e1466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel1a-content']/div/div/div/div</value>
      <webElementGuid>0b5889fc-cb88-4f8f-bb14-2524bf57bf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>1df7e197-6b81-428d-b755-2246ffd17cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Testing TaskHigh23:59, 04-01-25' or . = 'Testing TaskHigh23:59, 04-01-25')]</value>
      <webElementGuid>6024d142-2c73-49f6-a19c-3a26ce90c115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
