<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign upUsernameUsernameEmailEmailPasswo_87bac7</name>
   <tag></tag>
   <elementGuidId>a145c972-73b0-4323-8844-ea9f436c4f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-62o24s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SignUpForm']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sign upUsername *Username *Email *Email *Password *Password *Confirm Password *C&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4a650cc-75b8-4921-87d3-934b5b1b0618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-62o24s</value>
      <webElementGuid>afd272f4-04c5-45ca-a0b7-6ca53467ee05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign upUsername *Username *Email *Email *Password *Password *Confirm Password *Confirm Password *Create AccountEmail is invalid!Already had an account? Log in</value>
      <webElementGuid>cb11608a-6027-4d34-9bdb-bdac5f1b83f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SignUpForm&quot;)/div[@class=&quot;MuiBox-root css-62o24s&quot;]</value>
      <webElementGuid>96ebdaaa-1c18-45a9-b936-09e87295f03c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SignUpForm']/div</value>
      <webElementGuid>4219e3d5-7f06-4b75-9442-bf0092820f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to FocusTask'])[1]/following::div[2]</value>
      <webElementGuid>f719ef46-76f0-46f3-a525-f168ec7f6cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>8367f698-f99b-4e68-8557-79e1f871068b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign upUsername *Username *Email *Email *Password *Password *Confirm Password *Confirm Password *Create AccountEmail is invalid!Already had an account? Log in' or . = 'Sign upUsername *Username *Email *Email *Password *Password *Confirm Password *Confirm Password *Create AccountEmail is invalid!Already had an account? Log in')]</value>
      <webElementGuid>91d1fa94-965d-4035-8a06-56585cbcd34b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
