<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign upUsernameUsernameEmailEmailPasswo_77c913</name>
   <tag></tag>
   <elementGuidId>c51d710b-0078-4e09-b272-fb336338a3cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SignUpForm']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-62o24s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sign upUsername *Username *Email *Email *Password *Password *Create AccountAlrea&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d9d4f9c-0c7e-4a7e-a9d3-ccabda6c3e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-62o24s</value>
      <webElementGuid>aedbb28d-3355-4f69-a7b9-12ece60a11ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign upUsername *Username *Email *Email *Password *Password *Create AccountAlready had an account? Log in</value>
      <webElementGuid>aecdedfc-06b7-4a31-8331-16d35c8be7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SignUpForm&quot;)/div[@class=&quot;MuiBox-root css-62o24s&quot;]</value>
      <webElementGuid>4c1a75cb-e9a1-42ec-9d2f-e7ffff49824d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SignUpForm']/div</value>
      <webElementGuid>9647edd4-bf47-4ad8-8598-b6ae70a5469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to FocusTask'])[1]/following::div[2]</value>
      <webElementGuid>87497085-1d46-4022-a68c-3bc6544ab1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>30d86e31-cdd4-4eed-8e9a-67246afe5895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign upUsername *Username *Email *Email *Password *Password *Create AccountAlready had an account? Log in' or . = 'Sign upUsername *Username *Email *Email *Password *Password *Create AccountAlready had an account? Log in')]</value>
      <webElementGuid>b6266b16-6f50-45ae-95ff-f424ef831734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
